version: "3"

networks:
  goexpert:

services:
  mysql:
    hostname: mysql
    container_name: mysql
    restart: on-failure
    platform: linux/amd64
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: goexpert
    ports:
      - 3306:3306
    networks:
      - goexpert
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
